
all : 
	@echo --
	@echo -- Build Core .................................
	@echo --	
	cd build/obj ; make all
	cp ./build/image/slos.bin /tftpboot/
	@echo --
	@echo -- Complete ...................................
	@echo --
